# Generated by Django 5.1.6 on 2025-04-08 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_your_table_id_alter_your_table_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="your_table",
            table=None,
        ),
    ]
