# Generated by Django 5.1.6 on 2025-04-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_your_table_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permissions",
            old_name="numVal",
            new_name="numval",
        ),
        migrations.AlterField(
            model_name="users",
            name="upermission",
            field=models.ForeignKey(
                db_column="upermission",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.permissions",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="address",
            field=models.ForeignKey(
                db_column="Address",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.address",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="catalog_number",
            field=models.CharField(
                db_column="Catalog # (day inventory)", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="cataloguer_name",
            field=models.CharField(db_column="Cataloger name", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="conservation_condition",
            field=models.ForeignKey(
                db_column="Conservation & condition",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.conservationtype",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="data_double_checked_by",
            field=models.CharField(
                db_column="Data entry double checked by ", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="date_catalogued",
            field=models.DateTimeField(db_column="Date Catalogued on"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="date_collected",
            field=models.DateTimeField(db_column="Accessor number (date collected)"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="date_excavated",
            field=models.DateTimeField(db_column="Date excavated (field bag date)"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="deformation_index",
            field=models.FloatField(db_column="Deformation Index"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="distance_from_datum",
            field=models.CharField(db_column="Distance from Datum", max_length=25),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="druhlcheck",
            field=models.CharField(db_column="Dr.Uhl Check", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="excavator",
            field=models.CharField(db_column="Excavator", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="form_object_type",
            field=models.ForeignKey(
                db_column="Form (object type)",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.formtype",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="found_at_depth",
            field=models.CharField(
                db_column="Found at Depth below surface (report UNIT. mm prefered)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="found_in_grid",
            field=models.ForeignKey(
                db_column="Found in grid",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.gridnames",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="height",
            field=models.CharField(db_column="Height (mm)", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="images",
            field=models.CharField(
                db_column="Image (add column for each additional image)", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="latitude",
            field=models.CharField(db_column="Latitude", max_length=20),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="length",
            field=models.FloatField(db_column="Length (mm)"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="location",
            field=models.CharField(db_column="Location", max_length=100),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="location_in_repository",
            field=models.CharField(db_column="Location in repository", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="longitude",
            field=models.CharField(db_column="Longitude", max_length=20),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="material_of_manufacture",
            field=models.ForeignKey(
                db_column="Material of manufactur",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.materialtype",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="measurement_diameter",
            field=models.FloatField(
                db_column="Measurements (diameter/circumference) - length"
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="measurement_notes",
            field=models.CharField(db_column="Measurement Notes", max_length=750),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="notes",
            field=models.CharField(db_column="Notes", max_length=500),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="object_dated_to",
            field=models.CharField(db_column="Object dated to", max_length=100),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="object_description",
            field=models.CharField(db_column="Object Description", max_length=1000),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="object_name",
            field=models.CharField(db_column="Object Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="organic_inorganic",
            field=models.ForeignKey(
                db_column="inorganic/organic",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.organicinorganic",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="owner",
            field=models.CharField(db_column="Owner", max_length=255),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="platlot",
            field=models.CharField(db_column="PLAT/LOT", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="printed_3d",
            field=models.ForeignKey(
                db_column="3D Printed",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.threedprintedtable",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="qsconcerns",
            field=models.CharField(db_column="Questions/ concerns ", max_length=100),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="quantity",
            field=models.CharField(db_column="Quantity", max_length=100),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="scanned_3d",
            field=models.ForeignKey(
                db_column="3D Scanned",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.threedscannedtable",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="scanned_by",
            field=models.CharField(db_column="Scanned By", max_length=100),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="sivilich_diameter",
            field=models.FloatField(db_column="Sivilich Diameter (in)"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="sources_for_id",
            field=models.CharField(db_column="SOURCES FOR ID", max_length=1000),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="species",
            field=models.ForeignKey(
                db_column="species",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.speciestype",
            ),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="storage_location",
            field=models.CharField(db_column="Storage Location", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="uhlflages",
            field=models.CharField(db_column="Uhl Flags", max_length=250),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="weight",
            field=models.FloatField(db_column="weight (grams)"),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="weight_notes",
            field=models.CharField(db_column="Weight Notes", max_length=50),
        ),
        migrations.AlterField(
            model_name="your_table",
            name="width",
            field=models.FloatField(db_column="Width (mm)"),
        ),
    ]
