# Generated by Django 5.1.6 on 2025-04-23 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_your_table_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(db_column='filepath', max_length=100)),
                ('your_table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.your_table')),
            ],
        ),
    ]
