# Generated by Django 5.1.6 on 2025-04-23 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_numval_permissions_numval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetable',
            name='id',
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='your_table_id',
            field=models.ForeignKey(db_column='your_table_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.your_table'),
        ),
    ]
