# Generated by Django 5.1.6 on 2025-04-24 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_imagetable_id_alter_imagetable_your_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagetable',
            name='your_table_id',
            field=models.ForeignKey(db_column='your_table_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.your_table'),
        ),
    ]
