# Generated by Django 5.1.6 on 2025-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_imagetable_id_alter_imagetable_your_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
