# Generated by Django 5.1.6 on 2025-04-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_imagetable_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetable',
            old_name='your_table_id',
            new_name='your_table',
        ),
    ]
