# Generated by Django 5.1.6 on 2025-04-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_imagetable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
