# Generated by Django 5.1.6 on 2025-04-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_your_table_id_imagetable_your_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetable',
            name='your_table',
        ),
        migrations.AddField(
            model_name='imagetable',
            name='your_table_id',
            field=models.ForeignKey(db_column='your_table_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.your_table'),
        ),
    ]
