# Generated by Django 5.1.6 on 2025-05-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_rename_your_table_id_imagetable_your_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="your_table",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
