# Generated by Django 5.1.6 on 2025-05-02 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_your_table_id"),
        ("myapp", "0009_remove_imagetable_your_table_and_more"),
    ]

    operations = []
