# Generated by Django 5.1.6 on 2025-05-04 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_merge_20250502_1849"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagetable",
            old_name="your_table_id",
            new_name="your_table",
        ),
    ]
