# Generated by Django 5.1.6 on 2025-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_rename_your_table_id_imagetable_your_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="your_table",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="artifacts/"),
        ),
    ]
