# Generated by Django 5.1.6 on 2025-12-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_your_table_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="your_table",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
