from django.db import models



class Artifact(models.Model):
    address = models.IntegerField()
    owner = models.CharField(max_length=9000)
    date_collected = models.DateTimeField()
    catalog_number = models.CharField(max_length=900)
    object_name = models.CharField(max_length=9000)
    scanned_3d = models.CharField(max_length=100)
    printed_3d = models.CharField(max_length=100)
    scanned_by = models.CharField(max_length=9000)
    date_excavated = models.DateTimeField()
    object_dated_to = models.DateTimeField()
    object_description = models.CharField(max_length=9000)
    inorganic_organic = models.IntegerField()
    species = models.IntegerField()
    material_of_manufacture = models.IntegerField()
    form_object_type = models.IntegerField()
    quantitiy = models.IntegerField()
    measurements = models.FloatField()
    length = models.FloatField()
    width = models.FloatField()
    height = models.FloatField()
    weight = models.FloatField()
    weight_notes = models.CharField(max_length=100)
    sivilich_diameter = models.FloatField()
    deformation_index = models.IntegerField()
    conservation_condition = models.CharField(max_length=100)
    cataloguer_name = models.CharField(max_length=100)
    date_catalogued = models.DateTimeField()
    location_in_repository= models.IntegerField()
    platlot = models.CharField(max_length=9000)
    found_at_depth = models.FloatField()
    longitude = models.FloatField()
    latitude = models.FloatField()
    distance_from_datum = models.CharField(max_length=90)
    found_in_grid = models.IntegerField()
    exacavator = models.CharField(max_length=90)
    notes = models.CharField(max_length=900)
    images = models.IntegerField()
    data_double_checked_by = models.IntegerField()
    qsconcerns = models.IntegerField()
    druhlcheck = models.IntegerField()
    sources_for_id = models.IntegerField()
    location = models.CharField(max_length=90)
    storage_location = models.CharField(max_length=90)
    uhlflages = models.CharField(max_length=90)
